[features]
seeds = false
skip-lint = false
[programs.localnet]
wall4 = "BX9L6J7pVq5QAGREr3adW63uVThdQ3VqJp9BnuwmjGNx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/am/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
