[features]
seeds = false
skip-lint = false
[programs.localnet]
counter = "DRhYJPdvfE1m1r3nxUhVzWNWoi9VRTYZJZZvDRDfHTmh"
wall4 = "BCM4NRYr5q65AqSsvCUqE9KRjqLpj1SLFzutrzEy2Kui"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
#test = "../node_modules/.bin/nx run anchor:jest"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
bind_address = "127.0.0.1"
